### ISSUE TITLE
Internal IBM link in example App home page

### ISSUE THREAD

**Issue by laredo** [IBM/wxflows#6]
Link referring to an internal IBM link 

https://github.com/IBM/wxflows/blob/16b1f6f4ff370ced17ec3002c9a9453cfad5b9ab/examples/rag-question-answer/app/src/App.jsx#L55-L57

May just need to change github.ibm.com to github.com

**Comment by jwalczyk** [comment]
Looks like commit eed2c03281d3c0e058bc33032ed284c3625b380c reverted this fix [here](https://github.com/IBM/wxflows/pull/8/files#diff-7a4da887749cdc2f70c1dd00de2c58a5b2d85a1a7a1b42ffc54d0bcc1ee9f7b5R55)
